// src/components/AdminMemberSelect.jsx
import React, { useState, useEffect } from 'react';
import { collection, getDocs } from "firebase/firestore";
import { db } from '../firebase';

export default function AdminMemberSelect({ onSelect }) {
  const [combinedMembers, setCombinedMembers] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);
  
  // NEW STATE: Toggle to show/hide inactive people
  const [showAll, setShowAll] = useState(false); 

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      
      const membersSnap = await getDocs(collection(db, "members"));
      const registered = membersSnap.docs.map(doc => ({
        uid: doc.id,
        type: 'registered',
        ...doc.data()
      }));

      const legacySnap = await getDocs(collection(db, "legacy_members"));
      const legacy = legacySnap.docs.map(doc => ({
        uid: "LEGACY_" + doc.id,
        realId: doc.id,
        type: 'legacy',
        ...doc.data()
      }));

      const all = [...registered, ...legacy].sort((a, b) => 
        (a.lastName || "").localeCompare(b.lastName || "")
      );
      
      setCombinedMembers(all);
      setLoading(false);
    };
    fetchData();
  }, []);

  const filteredMembers = combinedMembers.filter(m => {
    // 1. Check Status
    // If we are NOT showing all, and the member is NOT active, hide them.
    if (!showAll && m.status && m.status !== 'Active') return false;

    // 2. Check Search Term
    const search = searchTerm.toLowerCase();
    const fullString = `${m.firstName} ${m.lastName} ${m.firstName2 || ''} ${m.lastName2 || ''} ${m.email}`.toLowerCase();
    return fullString.includes(search);
  });

  return (
    <div className="bg-blue-50 p-4 rounded border border-blue-200 mb-6">
      <h3 className="text-sm font-bold text-blue-800 mb-2 uppercase tracking-wide">
        Admin Mode: Log hours for others
      </h3>
      
      {loading ? <p className="text-sm text-blue-600">Loading member list...</p> : (
        <div>
          {/* CONTROLS ROW */}
          <div className="flex flex-col md:flex-row gap-2 mb-2">
            <input 
              type="text"
              placeholder="Search by Name..."
              className="flex-1 p-2 border rounded border-blue-300 focus:outline-none focus:border-blue-500"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            
            {/* NEW CHECKBOX */}
            <label className="flex items-center gap-2 text-xs font-bold text-blue-800 cursor-pointer bg-white px-3 border border-blue-200 rounded hover:bg-blue-50">
              <input 
                type="checkbox" 
                checked={showAll}
                onChange={(e) => setShowAll(e.target.checked)}
              />
              Show Inactive
            </label>
          </div>

          <select 
            className="w-full p-2 border rounded bg-white"
            onChange={(e) => {
              const selected = combinedMembers.find(m => m.uid === e.target.value);
              onSelect(selected);
            }}
            size={filteredMembers.length > 10 ? 10 : Math.max(2, filteredMembers.length + 1)} 
          >
            <option value="">
              -- {searchTerm ? `Found ${filteredMembers.length} matches` : "Select a Member"} --
            </option>
            
            {filteredMembers.map(m => {
              let label = `${m.lastName}, ${m.firstName}`;
              if (m.firstName2) {
                if (m.lastName2 && m.lastName2 !== m.lastName) {
                   label += ` & ${m.lastName2}, ${m.firstName2}`;
                } else {
                   label += ` & ${m.firstName2}`;
                }
              }

              const status = m.type === 'legacy' ? "(Not Registered)" : "(Active)";
              const memType = m.membershipType ? `(${m.membershipType})` : "";
              
              // VISUAL CUE: If they are Inactive, show it in the name
              const memberStatus = m.status && m.status !== 'Active' ? `[${m.status.toUpperCase()}]` : "";
              
              return (
                <option key={m.uid} value={m.uid} className={`py-1 ${memberStatus ? 'text-gray-400' : ''}`}>
                  {memberStatus} {label} {status} {memType}
                </option>
              );
            })}
          </select>
        </div>
      )}
    </div>
  );
}

// src/components/admin/AdminMemberSelect.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { collection, getDocs } from "firebase/firestore"
import { db } from '../../firebase'

const emit = defineEmits(['select'])

const combinedMembers = ref([])
const searchTerm = ref("")
const loading = ref(true)
const showAll = ref(false)

onMounted(async () => {
  loading.value = true
  
  try {
    // 1. Fetch ALL members (Registered + Migrated Legacy)
    const membersSnap = await getDocs(collection(db, "members"))
    
    const all = membersSnap.docs.map(doc => {
      const d = doc.data()
      return {
        uid: doc.id,
        // If they were migrated, they likely have status: 'Unregistered'
        // We can treat that effectively as the old "legacy" type for display purposes
        ...d
      }
    })

    // 2. Sort Alphabetically
    all.sort((a, b) => (a.lastName || "").localeCompare(b.lastName || ""))
    
    combinedMembers.value = all
  } catch (err) {
    console.error("Error loading members:", err)
  }
  
  loading.value = false
})

const filteredMembers = computed(() => {
  return combinedMembers.value.filter(m => {
    // 1. Check Status
    // If "Show All" is unchecked, hide Inactive. 
    // (Note: You usually want to see 'Unregistered' people to add logs for them, 
    // so we typically only hide 'Inactive' explicitly).
    if (!showAll.value && m.status === 'Inactive') return false

    // 2. Check Search Term
    if (!searchTerm.value) return true
    
    const term = searchTerm.value.toLowerCase()
    const fullName = `${m.firstName} ${m.lastName}`.toLowerCase()
    const email = (m.email || "").toLowerCase()
    
    return fullName.includes(term) || email.includes(term)
  })
})

const handleSelect = (event) => {
  const uid = event.target.value
  if (!uid) {
    emit('select', null)
    return
  }
  const user = combinedMembers.value.find(m => m.uid === uid)
  emit('select', user)
}
</script>

<template>
  <div class="bg-blue-50 p-4 rounded border border-blue-100">
    <h3 class="font-bold text-blue-900 mb-2 text-sm uppercase">Select Member to Manage</h3>
    
    <div v-if="loading" class="text-xs text-gray-500 animate-pulse">
      Loading member list...
    </div>

    <div v-else class="space-y-3">
      <div class="flex gap-2">
        <input 
          type="text" 
          placeholder="Filter by name or email..." 
          class="flex-1 p-2 border rounded border-blue-300 focus:outline-none focus:border-blue-500"
          v-model="searchTerm"
        />
        
        <label class="flex items-center gap-2 text-xs font-bold text-blue-800 cursor-pointer bg-white px-3 border border-blue-200 rounded hover:bg-blue-50">
          <input 
            type="checkbox" 
            v-model="showAll"
          />
          Show Inactive
        </label>
      </div>

      <select 
        class="w-full p-2 border rounded bg-white"
        @change="handleSelect"
        :size="filteredMembers.length > 10 ? 10 : Math.max(2, filteredMembers.length + 1)"
      >
        <option value="">
          -- {{ searchTerm ? `Found ${filteredMembers.length} matches` : "Select a Member" }} --
        </option>
        
        <option 
          v-for="m in filteredMembers" 
          :key="m.uid" 
          :value="m.uid" 
          class="py-1"
          :class="{ 'text-gray-400': m.status === 'Inactive' }"
        >
          <template v-if="m.status && m.status !== 'Active'">
            ** 
          </template>
          
          {{ m.lastName }}, {{ m.firstName }} 
        </option>
      </select>
      
      <p class="text-xs text-blue-800 mt-1">
        * Select a user to view their profile and add logs.
      </p>
    </div>
  </div>
</template>
