// src/components/ProfileEditor.jsx
import React, { useState } from 'react';
import { doc, updateDoc } from "firebase/firestore";
import { db } from '../firebase';

export default function ProfileEditor({ targetUser, currentUserRole, onClose, onSave }) {
  // Initialize state with existing data or empty strings
  const [formData, setFormData] = useState({
    firstName: targetUser.firstName || '',
    lastName: targetUser.lastName || '',
    email: targetUser.email || '',
    address: targetUser.address || '',
    city: targetUser.city || '',
    state: targetUser.state || '',
    zip: targetUser.zip || '',
    phone: targetUser.phone || '',
    cellPhone: targetUser.cellPhone || '',
    membershipType: targetUser.membershipType || 'Regular',
    role: targetUser.role || 'member'
  });

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const userRef = doc(db, "members", targetUser.uid);
      await updateDoc(userRef, formData);
      onSave(formData); // Tell parent component to update UI
      onClose();
    } catch (err) {
      console.error(err);
      alert("Error updating profile: " + err.message);
    }
  };

  const isAdmin = currentUserRole === 'admin';

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white p-6 rounded shadow-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-4 border-b pb-2">
          <h2 className="text-xl font-bold">Edit Profile: {targetUser.email}</h2>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700">✕</button>
        </div>

        <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* --- BASIC INFO --- */}
          <div>
            <label className="block text-xs font-bold text-gray-600">First Name</label>
            <input name="firstName" value={formData.firstName} onChange={handleChange} className="w-full p-2 border rounded" required />
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-600">Last Name</label>
            <input name="lastName" value={formData.lastName} onChange={handleChange} className="w-full p-2 border rounded" required />
          </div>
          
          <div className="md:col-span-2">
            <label className="block text-xs font-bold text-gray-600">Street Address</label>
            <input name="address" value={formData.address} onChange={handleChange} className="w-full p-2 border rounded" />
          </div>

          <div>
            <label className="block text-xs font-bold text-gray-600">City</label>
            <input name="city" value={formData.city} onChange={handleChange} className="w-full p-2 border rounded" />
          </div>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className="block text-xs font-bold text-gray-600">State</label>
              <input name="state" value={formData.state} onChange={handleChange} className="w-full p-2 border rounded" />
            </div>
            <div>
              <label className="block text-xs font-bold text-gray-600">Zip</label>
              <input name="zip" value={formData.zip} onChange={handleChange} className="w-full p-2 border rounded" />
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold text-gray-600">Home Phone</label>
            <input name="phone" value={formData.phone} onChange={handleChange} className="w-full p-2 border rounded" />
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-600">Cell Phone</label>
            <input name="cellPhone" value={formData.cellPhone} onChange={handleChange} className="w-full p-2 border rounded" />
          </div>

          {/* --- ADMIN ONLY FIELDS --- */}
          <div className="md:col-span-2 border-t pt-4 mt-2">
            <h3 className="font-bold text-sm text-gray-500 mb-2">Membership Details</h3>
          </div>
          
          <div>
            <label className="block text-xs font-bold text-gray-600">Membership Type</label>
            <select 
              name="membershipType" 
              value={formData.membershipType} 
              onChange={handleChange} 
              disabled={!isAdmin}
              className={`w-full p-2 border rounded ${!isAdmin ? 'bg-gray-100 text-gray-500' : ''}`}
            >
              <option value="Regular">Regular</option>
              <option value="Household">Household</option>
              <option value="Associate">Associate</option>
              <option value="Lifetime">Lifetime</option>
              <option value="Junior">Junior</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold text-gray-600">System Role</label>
            <select 
              name="role" 
              value={formData.role} 
              onChange={handleChange} 
              disabled={!isAdmin} // ONLY ADMINS CAN CHANGE ROLES
              className={`w-full p-2 border rounded ${!isAdmin ? 'bg-gray-100 text-gray-500' : ''}`}
            >
              <option value="member">Member</option>
              <option value="admin">Admin</option>
            </select>
            {!isAdmin && <p className="text-[10px] text-gray-400 mt-1">Only Admins can change roles.</p>}
          </div>

          {/* --- BUTTONS --- */}
          <div className="md:col-span-2 flex justify-end gap-3 mt-4 border-t pt-4">
            <button type="button" onClick={onClose} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded">Cancel</button>
            <button type="submit" className="px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">Save Changes</button>
          </div>
        </form>
      </div>
    </div>
  );
}

// src/modules/members/ProfileEditor.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { doc, updateDoc } from "firebase/firestore"
import { db } from '@/firebase'

const props = defineProps({
  targetUser: {
    type: Object,
    required: true
  },
  currentUserRole: {
    type: String,
    required: true
  }
})

const emit = defineEmits(['close', 'save'])

const formData = ref({
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  address: '',
  city: '',
  state: '',
  zip: '',
  // Administrative Fields
  membershipType: 'Regular',
  role: 'member',
  status: 'Active'
})

const loading = ref(false)

// PERMISSIONS
const isAdmin = computed(() => props.currentUserRole === 'admin')
const isManager = computed(() => props.currentUserRole === 'manager')
const isStaff = computed(() => isAdmin.value || isManager.value)

onMounted(() => {
  // Clone data so we don't mutate the prop directly
  formData.value = { ...props.targetUser }
})

const handleSave = async () => {
  loading.value = true
  try {
    const userRef = doc(db, "members", props.targetUser.uid)
    
    // Create update object
    const updateData = {
      firstName: formData.value.firstName,
      lastName: formData.value.lastName,
      email: formData.value.email,
      phone: formData.value.phone || '',
      address: formData.value.address || '',
      city: formData.value.city || '',
      state: formData.value.state || '',
      zip: formData.value.zip || '',
    }

    // ONLY ADMINS can write these fields to the database
    // If a Manager somehow enabled the fields, this check adds a layer of safety (UI logic)
    if (isAdmin.value) {
      updateData.membershipType = formData.value.membershipType
      updateData.role = formData.value.role
      updateData.status = formData.value.status
    }

    await updateDoc(userRef, updateData)
    
    emit('save', updateData)
    emit('close')
    alert("Profile updated successfully.")
  } catch (err) {
    console.error("Error updating profile:", err)
    alert("Failed to update profile: " + err.message)
  }
  loading.value = false
}
</script>

<template>
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
    <div class="bg-white rounded shadow-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
      
      <div class="p-6 border-b flex justify-between items-center bg-gray-50">
        <h3 class="text-xl font-bold text-gray-800">Edit Profile: {{ formData.firstName }} {{ formData.lastName }}</h3>
        <button @click="$emit('close')" class="text-gray-500 hover:text-red-600 text-2xl font-bold">&times;</button>
      </div>

      <form @submit.prevent="handleSave" class="p-6 space-y-6">
        
        <div>
          <h4 class="text-sm font-bold text-gray-500 uppercase border-b pb-1 mb-3">Contact Information</h4>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-xs font-bold text-gray-700 mb-1">First Name</label>
              <input v-model="formData.firstName" class="w-full p-2 border rounded" required />
            </div>
            <div>
              <label class="block text-xs font-bold text-gray-700 mb-1">Last Name</label>
              <input v-model="formData.lastName" class="w-full p-2 border rounded" required />
            </div>
            <div>
              <label class="block text-xs font-bold text-gray-700 mb-1">Email</label>
              <input v-model="formData.email" type="email" class="w-full p-2 border rounded" required />
            </div>
            <div>
              <label class="block text-xs font-bold text-gray-700 mb-1">Phone</label>
              <input v-model="formData.phone" class="w-full p-2 border rounded" />
            </div>
          </div>
        </div>

        <div>
          <h4 class="text-sm font-bold text-gray-500 uppercase border-b pb-1 mb-3">Address</h4>
          <div class="space-y-3">
             <div>
              <label class="block text-xs font-bold text-gray-700 mb-1">Street Address</label>
              <input v-model="formData.address" class="w-full p-2 border rounded" />
            </div>
            <div class="grid grid-cols-3 gap-4">
              <div class="col-span-1">
                <label class="block text-xs font-bold text-gray-700 mb-1">City</label>
                <input v-model="formData.city" class="w-full p-2 border rounded" />
              </div>
              <div>
                <label class="block text-xs font-bold text-gray-700 mb-1">State</label>
                <input v-model="formData.state" class="w-full p-2 border rounded" />
              </div>
              <div>
                <label class="block text-xs font-bold text-gray-700 mb-1">Zip</label>
                <input v-model="formData.zip" class="w-full p-2 border rounded" />
              </div>
            </div>
          </div>
        </div>

        <div v-if="isStaff" class="bg-blue-50 p-4 rounded border border-blue-200">
          <div class="flex justify-between items-center border-b border-blue-200 pb-2 mb-3">
            <h4 class="text-sm font-bold text-blue-900 uppercase">Membership Status</h4>
            <span v-if="!isAdmin" class="text-xs bg-gray-200 text-gray-600 px-2 py-1 rounded flex items-center gap-1">
              🔒 View Only (Admin Required)
            </span>
          </div>
          
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            
            <div>
              <label class="block text-xs font-bold text-blue-800 mb-1">Status</label>
              <select 
                v-model="formData.status" 
                class="w-full p-2 border rounded bg-white disabled:bg-gray-100 disabled:text-gray-500"
                :disabled="!isAdmin"
              >
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
              </select>
            </div>

            <div>
              <label class="block text-xs font-bold text-blue-800 mb-1">Type</label>
              <select 
                v-model="formData.membershipType" 
                class="w-full p-2 border rounded bg-white disabled:bg-gray-100 disabled:text-gray-500"
                :disabled="!isAdmin"
              >
                <option value="Regular">Regular</option>
                <option value="Household">Household</option>
                <option value="Applicant">Applicant</option>
                <option value="Associate">Associate</option>
                <option value="Life">Lifetime</option>
                <option value="Inactive">Inactive</option>
              </select>
            </div>

            <div>
              <label class="block text-xs font-bold text-blue-800 mb-1">System Role</label>
              <select 
                v-model="formData.role" 
                class="w-full p-2 border rounded bg-white disabled:bg-gray-100 disabled:text-gray-500"
                :disabled="!isAdmin"
              >
                <option value="member">Member</option>
                <option value="manager">Manager</option>
                <option value="admin">Admin</option>
              </select>
            </div>

          </div>
        </div>

        <div class="flex justify-end pt-4 border-t gap-3">
          <button type="button" @click="$emit('close')" class="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded">Cancel</button>
          <button type="submit" class="px-6 py-2 bg-blue-600 text-white font-bold rounded hover:bg-blue-700 shadow" :disabled="loading">
            {{ loading ? 'Saving...' : 'Save Changes' }}
          </button>
        </div>

      </form>
    </div>
  </div>
</template>
