// src/components/VolunteerLogs.jsx
import React, { useState, useEffect } from 'react';
import { collection, addDoc, query, where, getDocs, doc, deleteDoc, updateDoc, arrayUnion } from "firebase/firestore";
import { db, auth } from '../firebase'; // Import Auth to know WHO is editing
import { calculateRewards } from '../utils';

export default function VolunteerLogs({ user, currentUserRole }) {
  const [logs, setLogs] = useState([]);
  const [date, setDate] = useState('');
  const [hours, setHours] = useState('');
  const [activity, setActivity] = useState('');
  const [editingId, setEditingId] = useState(null);
  const [loading, setLoading] = useState(false);
  
  // New State for History Viewer
  const [viewingHistory, setViewingHistory] = useState(null); // Stores the log object to view

  const getCollectionRef = () => {
    if (user.type === 'legacy') {
      return collection(db, "legacy_members", user.realId, "legacyLogs");
    } else {
      return collection(db, "logs");
    }
  };

  const getDocRef = (logId) => {
    if (user.type === 'legacy') {
      return doc(db, "legacy_members", user.realId, "legacyLogs", logId);
    } else {
      return doc(db, "logs", logId);
    }
  };

  const fetchLogs = async () => {
    if (!user) return;
    setLoading(true);
    setLogs([]);

    try {
      let data = [];
      if (user.type === 'legacy') {
        const snap = await getDocs(getCollectionRef());
        data = snap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      } else {
        const q = query(collection(db, "logs"), where("memberId", "==", user.uid));
        const snap = await getDocs(q);
        data = snap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      }
      
      data.sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0));
      setLogs(data);
    } catch (err) {
      console.error("Error fetching logs:", err);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchLogs();
  }, [user]);

  const toggleRollover = async (log) => {
    try {
      const newVal = !log.applyToNextYear;
      await updateDoc(getDocRef(log.id), {
        applyToNextYear: newVal
      });
      setLogs(prev => prev.map(l => l.id === log.id ? { ...l, applyToNextYear: newVal } : l));
    } catch (err) {
      alert("Error: " + err.message);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!date || !hours || !activity) return;
    
    const numHours = parseFloat(hours);
    let status = "approved";

    if (numHours > 8) {
      const confirm = window.confirm("You are logging more than 8 hours for a single day. Is this correct?");
      if (!confirm) return;
      status = "pending"; 
    }

    try {
      if (editingId) {
         // --- EDIT MODE WITH HISTORY TRACKING ---
         const logRef = getDocRef(editingId);
         const newStatus = currentUserRole === 'admin' ? 'approved' : 'pending';
         
         // 1. Find the original log locally to snapshot it
         const originalLog = logs.find(l => l.id === editingId);
         
         // 2. Create History Entry
         const historyEntry = {
            changedAt: new Date().toISOString(),
            changedBy: auth.currentUser.email, // The person logged in RIGHT NOW
            oldData: {
               date: originalLog.date,
               hours: originalLog.hours,
               activity: originalLog.activity
            }
         };

         // 3. Update Doc with new data AND push to history array
         await updateDoc(logRef, {
           date, 
           hours: numHours, 
           activity, 
           status: newStatus,
           history: arrayUnion(historyEntry) // <--- MAGIC HAPPENS HERE
         });
         setEditingId(null);
      } else {
         // CREATE MODE
         const newLog = {
           date,
           hours: numHours,
           activity,
           status,
           submittedAt: new Date(),
           applyToNextYear: false,
           history: [] // Initialize empty history
         };
         
         if (user.type !== 'legacy') {
           newLog.memberId = user.uid;
         }

         await addDoc(getCollectionRef(), newLog);
      }
      
      setDate(''); setHours(''); setActivity('');
      fetchLogs(); 
    } catch (err) {
      console.error("Error saving log:", err);
      alert("Failed to save log");
    }
  };

  const handleEdit = (log) => {
    setDate(log.date);
    setHours(log.hours);
    setActivity(log.activity);
    setEditingId(log.id);
  };

  const handleDelete = async (id) => {
    if(window.confirm("Are you sure you want to delete this entry?")) {
      await deleteDoc(getDocRef(id));
      fetchLogs();
    }
  };

  const stats = calculateRewards(logs);

  return (
    <div className="mt-8">
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div className="bg-indigo-600 text-white p-4 rounded shadow">
          <h4 className="text-indigo-200 text-xs font-bold uppercase">{stats.year} Fiscal Hours</h4>
          <p className="text-3xl font-bold">{stats.totalHours}</p>
          <p className="text-xs opacity-75 mt-1">(Oct 1 - Sep 30)</p>
        </div>
        <div className="bg-white p-4 rounded shadow border-l-4 border-green-500">
          <h4 className="text-gray-500 text-xs font-bold uppercase">Vouchers Earned</h4>
          <p className="text-3xl font-bold text-gray-800">{stats.vouchers}</p>
        </div>
        <div className="bg-white p-4 rounded shadow border-l-4 border-blue-500">
          <h4 className="text-gray-500 text-xs font-bold uppercase">Membership Status</h4>
          <p className="text-xl font-bold text-gray-800 mt-1">{stats.membershipStatus}</p>
        </div>
      </div>

      <h3 className="text-xl font-bold mb-4 text-gray-800">
         {editingId ? "Edit Entry" : "Log New Hours"}
      </h3>
      
      <form onSubmit={handleSubmit} className={`p-4 rounded mb-6 grid grid-cols-1 md:grid-cols-4 gap-4 items-end ${editingId ? 'bg-yellow-50 border border-yellow-400' : 'bg-gray-100'}`}>
        <div>
          <label className="block text-xs font-bold text-gray-600 mb-1">Date</label>
          <input type="date" value={date} onChange={e => setDate(e.target.value)} className="w-full p-2 border rounded" />
        </div>
        <div className="md:col-span-2">
          <label className="block text-xs font-bold text-gray-600 mb-1">Activity</label>
          <input type="text" value={activity} onChange={e => setActivity(e.target.value)} className="w-full p-2 border rounded" />
        </div>
        <div>
          <label className="block text-xs font-bold text-gray-600 mb-1">Hours</label>
          <div className="flex gap-2">
            <input type="number" step="0.25" value={hours} onChange={e => setHours(e.target.value)} className="w-full p-2 border rounded" />
            <button type="submit" className={`${editingId ? 'bg-yellow-600' : 'bg-green-600'} text-white px-4 py-2 rounded hover:opacity-90`}>
              {editingId ? "Update" : "Add"}
            </button>
          </div>
        </div>
        {editingId && (
          <div className="col-span-4 text-right">
            <button type="button" onClick={() => { setEditingId(null); setDate(''); setHours(''); setActivity(''); }} className="text-sm text-gray-500 underline">Cancel Edit</button>
          </div>
        )}
      </form>

      <div className="bg-white rounded shadow overflow-x-auto">
        <table className="w-full text-left min-w-[600px]">
          <thead className="bg-gray-200">
            <tr>
              <th className="p-3 text-sm font-semibold text-gray-700">Date</th>
              <th className="p-3 text-sm font-semibold text-gray-700">Activity</th>
              <th className="p-3 text-sm font-semibold text-gray-700 text-right">Hours</th>
              <th className="p-3 text-sm font-semibold text-gray-700">Status</th>
              {currentUserRole === 'admin' && <th className="p-3 text-sm font-semibold text-gray-700 text-center">Roll Over</th>}
              <th className="p-3 text-sm font-semibold text-gray-700">Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan="6" className="p-4 text-center text-gray-500">Loading...</td></tr>
            ) : logs.length === 0 ? (
              <tr><td colSpan="6" className="p-4 text-center text-gray-500">No hours logged yet.</td></tr>
            ) : (
              logs.map(log => (
                <tr key={log.id} className={`border-t hover:bg-gray-50 ${log.applyToNextYear ? 'bg-purple-50' : ''}`}>
                   <td className="p-3">{log.date}</td>
                   <td className="p-3">{log.activity}</td>
                   <td className="p-3 text-right font-mono">{log.hours}</td>
                   <td className="p-3">
                    <span className={`text-xs px-2 py-1 rounded-full ${log.status === 'pending' ? 'bg-orange-100 text-orange-800' : 'bg-green-100 text-green-800'}`}>
                      {log.status || 'approved'}
                    </span>
                   </td>
                   
                   {currentUserRole === 'admin' && (
                    <td className="p-3 text-center">
                      <input 
                        type="checkbox" 
                        checked={log.applyToNextYear || false} 
                        onChange={() => toggleRollover(log)}
                        className="cursor-pointer w-4 h-4"
                      />
                    </td>
                   )}

                   <td className="p-3 text-sm whitespace-nowrap flex items-center">
                    <button onClick={() => handleEdit(log)} className="text-blue-600 hover:underline mr-3">Edit</button>
                    <button onClick={() => handleDelete(log.id)} className="text-red-600 hover:underline mr-3">Delete</button>
                    
                    {/* HISTORY BUTTON (Only shows if history exists) */}
                    {log.history && log.history.length > 0 && (
                      <button 
                        onClick={() => setViewingHistory(log)} 
                        className="text-gray-500 hover:text-gray-700 text-xs border border-gray-300 px-2 py-1 rounded bg-gray-50"
                        title="View Edit History"
                      >
                        🕒 History
                      </button>
                    )}
                   </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* --- HISTORY MODAL --- */}
      {viewingHistory && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-6 rounded shadow-lg w-full max-w-md">
            <div className="flex justify-between items-center mb-4 border-b pb-2">
              <h3 className="font-bold text-lg">Edit History</h3>
              <button onClick={() => setViewingHistory(null)} className="text-gray-500 hover:text-gray-800">✕</button>
            </div>
            
            <div className="max-h-[300px] overflow-y-auto space-y-4">
              {viewingHistory.history.map((entry, i) => (
                <div key={i} className="text-sm border-l-2 border-gray-300 pl-3">
                  <p className="text-gray-500 text-xs">
                    {new Date(entry.changedAt).toLocaleString()} by <span className="font-semibold">{entry.changedBy}</span>
                  </p>
                  <div className="mt-1 text-gray-700 bg-gray-50 p-2 rounded">
                    <p className="font-bold text-xs uppercase text-gray-400 mb-1">Previous Version:</p>
                    <p>Date: {entry.oldData.date}</p>
                    <p>Activity: {entry.oldData.activity}</p>
                    <p>Hours: {entry.oldData.hours}</p>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-4 text-right">
              <button onClick={() => setViewingHistory(null)} className="bg-gray-200 text-gray-800 px-4 py-2 rounded hover:bg-gray-300">Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/modules/members/VolunteerLogs.vue
<script setup>
import { ref, watch, computed } from 'vue'
import { collection, query, where, getDocs, deleteDoc, doc, getDoc, updateDoc, addDoc } from "firebase/firestore"
import { db, auth } from '../../firebase'
import { getFiscalYear, formatDateStandard, parseDateSafe } from '../../utils'
import NotificationToast from '../../components/common/NotificationToast.vue'
import ConfirmModal from '../../components/common/ConfirmModal.vue'

const props = defineProps({
  user: { type: Object, required: true },
  currentUserRole: { type: String, default: 'member' }
})

const emit = defineEmits(['stats-update', 'edit-log'])

const logs = ref([])
const loading = ref(false)
const showSheetModal = ref(false)
const activeSheetUrl = ref('')
const loadingSheet = ref(false)
const toast = ref({ visible: false, message: '', type: 'success' })
const confirmState = ref({ isOpen: false, title: '', message: '', resolve: null })

// --- HELPERS ---
const targetUserId = computed(() => props.user.id || props.user.uid || null)
const isLegacyMember = computed(() => props.user.type === 'legacy')

const showToast = (msg, type = 'success') => {
  toast.value = { visible: true, message: msg, type }
}

const openConfirmModal = (title, message) => {
  return new Promise((resolve) => {
    confirmState.value = { isOpen: true, title, message, resolve }
  })
}

const handleConfirm = () => {
  if (confirmState.value.resolve) confirmState.value.resolve(true)
  confirmState.value.isOpen = false
}

const handleCancel = () => {
  if (confirmState.value.resolve) confirmState.value.resolve(false)
  confirmState.value.isOpen = false
}


const canManageLog = (log) => {
  const role = (props.currentUserRole || '').toLowerCase()
  if (['admin', 'manager'].includes(role)) return true
  if (auth.currentUser && auth.currentUser.uid === log.memberId) return true
  return false
}


// --- FETCH ---
const fetchLogs = async () => {
  if (!targetUserId.value) return
  loading.value = true
  logs.value = []
  
  const currentFY = getFiscalYear(new Date())
  let fyRegularHours = 0
  let fyBlueRibbonHours = 0

  try {
    let snap
    // EXPLICIT CHECK: Are we in Legacy Mode?
    const legacyMode = isLegacyMember.value

    if (legacyMode) {
      snap = await getDocs(collection(db, "legacy_members", targetUserId.value, "legacyLogs"))
    } else {
      const q = query(collection(db, "logs"), where("memberId", "==", targetUserId.value))
      snap = await getDocs(q)
    }
    
    const rawLogs = snap.docs.map(d => {
      const data = d.data()
      const logDate = parseDateSafe(data.date)
      const logFY = getFiscalYear(logDate)
      const hours = parseFloat(data.hours || 0)
      
      const isBlueRibbon = data.isMaintenance === true || ['Maintenance', 'Cleaning'].includes(data.type)
      const countsForCurrentFY = (logFY === currentFY) || (logFY === currentFY - 1 && data.applyToNextYear === true)

      if (data.status === 'approved' && countsForCurrentFY) {
        isBlueRibbon ? (fyBlueRibbonHours += hours) : (fyRegularHours += hours)
      }

      return { 
        id: d.id, 
        ...data,
        sheetId: data.sourceSheetId || data.sheetId || null,
        isBlueRibbon,
        parsedDate: logDate,
        // CRITICAL: Tag the log so the Edit Form knows where it lives
        isLegacy: legacyMode 
      }
    })

    logs.value = rawLogs.sort((a, b) => b.parsedDate.getTime() - a.parsedDate.getTime())

    const regularVouchers = fyRegularHours >= 50 ? Math.floor(fyRegularHours / 25) : 0
    const blueRibbonVouchers = Math.floor(fyBlueRibbonHours / 8)

    emit('stats-update', {
      year: currentFY,
      regularHours: fyRegularHours,
      regularVouchers,
      blueRibbonHours: fyBlueRibbonHours,
      blueRibbonVouchers
    })

  } catch (err) {
    console.error(err)
    showToast("Error loading logs", "error")
  }
  loading.value = false
}

// --- ACTIONS ---
const archiveAndDeleteLog = async (log) => {
  if (!await openConfirmModal("Delete Entry?", "Cannot be undone.")) return
  try {
    const by = auth.currentUser ? auth.currentUser.email : 'Unknown'
    await addDoc(collection(db, "archived_logs"), { ...log, originalId: log.id, archivedAt: new Date(), archivedBy: by })

    if (log.isLegacy || isLegacyMember.value) {
       await deleteDoc(doc(db, "legacy_members", targetUserId.value, "legacyLogs", log.id))
    } else {
       await deleteDoc(doc(db, "logs", log.id))
    }
    showToast("Deleted.", "success")
    fetchLogs() 
  } catch (err) { showToast(err.message, "error") }
}

const rolloverLog = async (log) => {
  const currentFY = getFiscalYear(parseLogDate(log.date))
  const targetFY = currentFY + 1
  
  // Select Ref based on log tag OR user state
  let docRef
  if (log.isLegacy || isLegacyMember.value) {
    docRef = doc(db, "legacy_members", targetUserId.value, "legacyLogs", log.id)
  } else {
    docRef = doc(db, "logs", log.id)
  }
  
  if (log.applyToNextYear) {
    if (!await openConfirmModal("Remove Rollover?", "Remove from next year?")) return
    try {
      await updateDoc(docRef, { applyToNextYear: false })
      showToast("Rollover removed.", "success")
      fetchLogs()
    } catch(err) { showToast(err.message, "error") }
    return
  }

  if (!await openConfirmModal("Apply Rollover?", `Apply to FY ${targetFY}?`)) return
  try {
    await updateDoc(docRef, { applyToNextYear: true })
    showToast(`Applied to FY ${targetFY}!`, "success")
    fetchLogs()
  } catch (err) { showToast(err.message, "error") }
}

const viewSheet = async (sheetId) => {
  if (!sheetId) return
  loadingSheet.value = true
  activeSheetUrl.value = ''
  showSheetModal.value = true
  try {
    const docSnap = await getDoc(doc(db, "volunteer_sheets", sheetId))
    if (docSnap.exists()) activeSheetUrl.value = docSnap.data().imageUrl
    else { showToast("Sheet not found.", "error"); showSheetModal.value = false }
  } catch (err) { showToast("Error loading sheet.", "error"); showSheetModal.value = false }
  loadingSheet.value = false
}

watch(targetUserId, fetchLogs, { immediate: true })
defineExpose({ fetchLogs })
</script>

<template>
  <div class="bg-white rounded shadow border border-gray-200 overflow-hidden relative">
    <NotificationToast v-if="toast.visible" :message="toast.message" :type="toast.type" @close="toast.visible = false" />
    <ConfirmModal :isOpen="confirmState.isOpen" :title="confirmState.title" :message="confirmState.message" @confirm="handleConfirm" @cancel="handleCancel" />

    <div class="bg-gray-50 p-4 border-b flex justify-between items-center">
      <h3 class="font-bold text-gray-700">📜 Work History</h3>
      <button @click="fetchLogs" class="text-xs text-blue-600 hover:underline">Refresh</button>
    </div>

    <div v-if="loading" class="p-8 text-center text-gray-400">Loading history...</div>
    <div v-else-if="logs.length === 0" class="p-8 text-center text-gray-500 italic">No hours logged yet.</div>

    <div v-else class="max-h-96 overflow-y-auto">
      <table class="w-full text-sm text-left">
        <thead class="bg-gray-100 text-gray-500 uppercase text-xs sticky top-0 z-10">
          <tr>
            <th class="p-3">Date</th>
            <th class="p-3">Activity</th>
            <th class="p-3 text-right">Hours</th>
            <th class="p-3 text-center">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y">
          <tr v-for="log in logs" :key="log.id" class="hover:bg-gray-50 group">
            <td class="p-3 whitespace-nowrap text-gray-600 align-top font-mono text-xs">{{ formatDateStandard(log.date) }}</td>
            <td class="p-3 text-gray-800 align-top">
              <div class="flex flex-wrap items-center gap-2 mb-1">
                <span class="font-bold text-xs uppercase text-gray-500">{{ log.type }}</span>
                <span v-if="log.sheetId" @click="viewSheet(log.sheetId)" class="text-[10px] uppercase font-bold bg-gray-100 hover:bg-gray-200 text-gray-600 px-1.5 py-0.5 rounded border border-gray-300 cursor-pointer flex items-center gap-1 transition-colors select-none" title="Click to View Original Sheet">📄 Sheet #{{ log.sheetId.slice(-4) }}</span>
                <span v-if="log.isBlueRibbon" class="text-[10px] uppercase font-bold bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded border border-blue-200">🏆 Blue Ribbon</span>
                <span v-if="log.applyToNextYear" class="text-[10px] uppercase font-bold bg-purple-100 text-purple-700 px-1.5 py-0.5 rounded border border-purple-200">↪️ Rolled Over</span>
                <span v-if="log.status === 'pending'" class="text-[10px] uppercase font-bold bg-yellow-100 text-yellow-700 px-1.5 py-0.5 rounded border border-yellow-200">⏳ Pending</span>
              </div>
              <div class="text-sm text-gray-700 leading-snug">
                {{ log.activity || log.description || '(No details)' }}
                <span class="text-[10px] text-gray-400 font-mono ml-2 select-all">(ID: {{ log.id }})</span>
              </div>
            </td>
            <td class="p-3 text-right font-mono font-bold align-top" :class="log.isBlueRibbon ? 'text-blue-600' : 'text-gray-700'">{{ log.hours }}</td>
            <td class="p-3 text-center align-top min-w-[120px]">
              <div v-if="canManageLog(log)" class="flex flex-wrap justify-center gap-2">
                <button v-if="['admin', 'manager'].includes(currentUserRole.toLowerCase())" @click="rolloverLog(log)" class="text-purple-600 hover:text-purple-800 bg-purple-50 hover:bg-purple-100 px-2 py-1 rounded text-xs font-bold border border-purple-200">↪️</button>
                <button @click="$emit('edit-log', log)" class="text-blue-500 hover:text-blue-700 bg-blue-50 hover:bg-blue-100 px-2 py-1 rounded text-xs font-bold border border-blue-200">Edit</button>
                <button @click="archiveAndDeleteLog(log)" class="text-red-500 hover:text-red-700 bg-red-50 hover:bg-red-100 px-2 py-1 rounded text-xs font-bold border border-red-200">×</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div v-if="showSheetModal" class="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-fade-in">
       <div class="bg-white rounded-lg shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
          <div class="bg-gray-800 p-3 flex justify-between items-center text-white shrink-0">
             <h3 class="font-bold text-sm">Original Sign-In Sheet</h3>
             <button @click="showSheetModal = false" class="hover:text-gray-300 font-bold px-2">Close</button>
          </div>
          <div class="p-0 flex-grow overflow-auto bg-gray-100 flex items-center justify-center relative">
             <div v-if="loadingSheet" class="text-gray-500 animate-pulse font-bold">Loading Image...</div>
             <img v-else-if="activeSheetUrl" :src="activeSheetUrl" class="max-w-full h-auto object-contain shadow-lg" />
          </div>
       </div>
    </div>
  </div>
</template>
